# Generated by Django 5.1.3 on 2024-11-18 14:07

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True,
                        help_text="Укажите место выполнения привычки",
                        max_length=100,
                        null=True,
                        verbose_name="Место выполнения привычки",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Во сколько необходимо выполнять привычку",
                        null=True,
                        verbose_name="Время начала",
                    ),
                ),
                (
                    "habit",
                    models.CharField(
                        help_text="Опишите привычку",
                        max_length=255,
                        verbose_name="Привычка",
                    ),
                ),
                (
                    "sing_habit",
                    models.BooleanField(
                        help_text="Укажите, если привычка с вознаграждением",
                        verbose_name="Признак привычки",
                    ),
                ),
                (
                    "periodicity",
                    models.CharField(
                        choices=[("DAY", "Day"), ("MONTH", "Month")],
                        default="Day",
                        max_length=10,
                        verbose_name="Периодичность привычки",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Вознаграждение за привычку",
                    ),
                ),
                (
                    "time_to_complete",
                    models.TimeField(
                        default=datetime.timedelta(seconds=120),
                        verbose_name="Время выполнения привычки",
                    ),
                ),
                (
                    "sing_publicity",
                    models.BooleanField(
                        default=False,
                        help_text="Отметьте, если нужно опубликовать",
                        verbose_name="Опубликовано",
                    ),
                ),
            ],
        ),
    ]
